### ISSUE TITLE
/root/workspace/src/github.com/nohupped/ADtoLDAP/gosyncmodules/CheckPerm.go:23: undefined: user.LookupGroupId

### ISSUE THREAD

**Issue by shandersonvieira** [nohupped/ADtoLDAP#10]
Hi,

The command below does not work, would you help me?

> go get github.com/nohupped/ADtoLDAP

Return:

`/root/workspace/src/github.com/nohupped/ADtoLDAP/gosyncmodules/CheckPerm.go:23: undefined: user.LookupGroupId
`

**Comment by nohupped** [comment]
Can you make sure if you are using the latest go version? I believe the function user.LookupGroupId was introduced in one of the recent versions. They have the doc [here](https://golang.org/doc/go1.9)
