### ISSUE TITLE
Not able to `go get`

### ISSUE THREAD

**Issue by hxvxt2** [nohupped/ADtoLDAP#17]
Hi There,

I am facing some trouble during installation.  Could you please guide me what I might be doing wrong here?

`❯ go get -f -u -v  github.com/nohupped/ADtoLDAP`

```
github.com/nohupped/ADtoLDAP (download)
github.com/nohupped/glog (download)
gopkg.in/ini.v1 (download)
gopkg.in/ldap.v2 (download)
gopkg.in/asn1-ber.v1 (download)
github.com/nohupped/ADtoLDAP/gosyncmodules
# github.com/nohupped/ADtoLDAP/gosyncmodules
src/github.com/nohupped/ADtoLDAP/gosyncmodules/logger.go:29:20: cannot use glog.DebugLevel (type uint) as type *uint in argument to logger.SetLogLevel
src/github.com/nohupped/ADtoLDAP/gosyncmodules/logger.go:36:21: cannot use glog.ErrorLevel (type uint) as type *uint in argument to logger.SetLogLevel
src/github.com/nohupped/ADtoLDAP/gosyncmodules/logger.go:39:21: cannot use glog.WarnLevel (type uint) as type *uint in argument to logger.SetLogLevel
src/github.com/nohupped/ADtoLDAP/gosyncmodules/logger.go:42:21: cannot use glog.InfoLevel (type uint) as type *uint in argument to logger.SetLogLevel
src/github.com/nohupped/ADtoLDAP/gosyncmodules/logger.go:45:21: cannot use glog.DebugLevel (type uint) as type *uint in argument to logger.SetLogLevel
```

Thanks

**Comment by nohupped** [comment]
This is because the glog library had some breaking changes and this program was written before go modules were introduced. I will fix the logger issue soon. Thank you for pointing this out.

**Comment by nohupped** [comment]
Fixed by #18, #19 and #20 
Now that go mod is enabled, please make sure you have go version > 1.11

```bash
~/devel via 🐹 v1.14.2 via 🐘 v7.4.5 
[ 26-04-20::21:47:24 ] ❯ go get -f -u -v github.com/nohupped/ADtoLDAP          
github.com/nohupped/ADtoLDAP (download)
github.com/nohupped/glog (download)
gopkg.in/ini.v1 (download)
gopkg.in/ldap.v2 (download)
gopkg.in/asn1-ber.v1 (download)
github.com/nohupped/ADtoLDAP/syncer
github.com/nohupped/ADtoLDAP
~/devel via 🐹 v1.14.2 via 🐘 v7.4.5 took 23s 
[ 26-04-20::21:51:28 ] ❯ which ADtoLDAP
$GOBIN/ADtoLDAP
```

**Comment by hxvxt2** [comment]
Thanks for fixing this @nohupped. I am able to install it now. But what's that bit about `which ADtoLDAP`? I can't find any file with that name on my machine.  

```
> which ADtoLDAP 
ADtoLDAP not found
```

I also tried to look for `GOBIN`in my Go environment variables  `go env` looks like that's not set on my machine. Could that be the issue? 

Thanks

**Comment by nohupped** [comment]
From the [documentation](https://golang.org/cmd/go/),
> Executables are installed in the directory named by the GOBIN environment variable, which defaults to $GOPATH/bin or $HOME/go/bin if the GOPATH environment variable is not set. Executables in $GOROOT are installed in $GOROOT/bin or $GOTOOLDIR instead of $GOBIN.

So I believe you can find the binary inside your `$HOME/go/bin` directory even if you don't have `$GOBIN` variable exported. I can see it with `which ADtoLDAP` because `$GOBIN` is added to my `$PATH` variables.
