### ISSUE TITLE
Module path should be "github.com/nohupped/ADtoLDAP", not "ADtoLDAP"

### ISSUE THREAD

**Issue by KateGo520** [nohupped/ADtoLDAP#22]
## Background
Module path is inconsistent with go import path.
GO111MODULE=on, run `go get github.com/nohupped/ADtoLDAP`:

```
go: downloading github.com/nohupped/ADtoLDAP v0.0.0-20200426135055-207bf29e0c6b
go: github.com/nohupped/ADtoLDAP upgrade => v0.0.0-20200426135055-207bf29e0c6b
go get: github.com/nohupped/ADtoLDAP@v0.0.0-20200426135055-207bf29e0c6b: parsing go.mod:
        module declares its path as: ADtoLDAP
                but was required as: github.com/nohupped/ADtoLDAP 
```

###  Fix the module path:
1) Rename the module path to "github.com/nohupped/ADtoLDAP": https://github.com/nohupped/ADtoLDAP/blob/master/go.mod#L1 :
```
module github.com/nohupped/ADtoLDAP
go 1.13
require (
	…
) 
```
2) Warning the users not to use the module, get "github.com/nohupped/ADtoLDAP" in GOPATH mode.

**Comment by KateGo520** [comment]
@nohupped  Could you help me review this issue? Thx :p

**Comment by nohupped** [comment]
Thank you for reporting this @KateGo520 The suggested fix is merged.

**Comment by KateGo520** [comment]
@nohupped  Thank you for your contribution. That helps a lot.
