### ISSUE TITLE
Requires root-level access to run

### ISSUE THREAD

**Issue by eigood** [nohupped/ADtoLDAP#3]
This is because the log file is hard-coded to /var/log/ldapsync.log.  Further complicated because the logging is started *before* the command line is parsed, and before the config file is loaded.

Nothing about this program requires root level access.  Just a config file to read, and 2 remote servers to talk to.

**Comment by nohupped** [comment]
Will change it as an option in the config file so that it need not be a hardcoded `/var/log/ldapsync.log`.
