### ISSUE TITLE
Requires config file to be owned by root

### ISSUE THREAD

**Issue by eigood** [nohupped/ADtoLDAP#5]
12:19:53 -0500 adam@tooz:/srv/development/openldap$ sudo /srv/development/go/bin/ADtoLDAP  -configfile test.ini 
test.ini not owned by root. Make it owned by root, and make it non-readable to groups and others.

Please note, that test.ini exists in the current folder.  I have to use sudo because of the previous requirement to access /var/log/ldapsync.log.

This program does not need to run as root, so shouldn't be forcing root ownership.

**Comment by nohupped** [comment]
#3 will fix this.

**Comment by eigood** [comment]
The config file should be owned by the user that is running the program.  Not root.  No need for --safe then either, as the 600 perms would be fine.

**Comment by nohupped** [comment]
I'd appreciate it if you can raise a pull request. If you are occupied, I will work on this over the weekend.

**Comment by nohupped** [comment]
@eigood if you can have a look at the pull request.
