### ISSUE TITLE
If settings do not exist in the config file, the program bails

### ISSUE THREAD

**Issue by eigood** [nohupped/ADtoLDAP#6]
I am not using tls/ssl to talk to the source AD server.  Aka, I am talking on port 389.  As such, I have commented out UseTLS, etc.  The program then says those values don't exist.

So, I then place UseTLS=false back into the config.  I then get an error about CRTPath not being readable(I copied the example from the README).  So I try to disable that option too, etc.

I can work around the CRTPath by setting it to /dev/null.  But it'd be nice if the program was more forgiving on missing options(I don't need any of the certification/ssl stuff in my environment, all communication is sent over a secure tunnel).

**Comment by nohupped** [comment]
Thank you for pointing this out. Will modify it.
